In [1]:
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix


In [11]:
df=pd.read_excel("C:/Users/Dell/Pictures/rndsampletrain.xlsx")
df=df[['row_index','content','final_sentiment']]

In [14]:
df.head()

row_index                                            content  \
0          0  Smell good, instant glow, long lasting freshne...   
1          1  Smell, freshness, spreadability, fairness, sof...   
2          2  Softness is good, smell is good, like the brig...   
3          3  Like the smell very much, softness good, non o...   
4          4  Softness, non oily feel, smell, spread evenly,...   

   final_sentiment  
0                1  
1                1  
2                1  
3                1  
4                1

In [13]:
#removing /d with , and (d) with space
df['content'] = df['content'].str.replace("/", ",")
#df['content'] = df['content'].str.replace("(d)", " ")


In [15]:
df.final_sentiment.value_counts()

1    251
0    105
Name: final_sentiment, dtype: int64

In [16]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix


X = df.content
y = df.final_sentiment
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42,stratify=y)

In [17]:
X_train.head()

53     It’s thick (d), it give dryness on skin (d), g...
1      Smell, freshness, spreadability, fairness, sof...
258                             No long lasting softness
195    Control dryness, give warming smooth, long las...
117    Good frag, it's required more to use (d), it's...
Name: content, dtype: object

In [18]:
y_train.value_counts()

1    176
0     73
Name: final_sentiment, dtype: int64

In [19]:
y_test.value_counts()

1    75
0    32
Name: final_sentiment, dtype: int64

In [20]:

#smote
nb = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', MultinomialNB()),
              ])
nb.fit(X_train, y_train)


from sklearn.metrics import classification_report
y_pred = nb.predict(X_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred))


accuracy 0.8691588785046729
              precision    recall  f1-score   support

           0       1.00      0.56      0.72        32
           1       0.84      1.00      0.91        75

   micro avg       0.87      0.87      0.87       107
   macro avg       0.92      0.78      0.82       107
weighted avg       0.89      0.87      0.86       107



In [21]:
y_pred # 9wrong in nb

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [22]:
np.array(y_test)

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [107]:
from sklearn.linear_model import SGDClassifier

sgd = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, max_iter=5, tol=None)),
               ])
sgd.fit(X_train, y_train)

y_pred = sgd.predict(X_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred))

accuracy 0.9252336448598131
              precision    recall  f1-score   support

           0       0.85      0.91      0.88        32
           1       0.96      0.93      0.95        75

   micro avg       0.93      0.93      0.93       107
   macro avg       0.91      0.92      0.91       107
weighted avg       0.93      0.93      0.93       107



In [113]:
# 2nd one:
from sklearn.linear_model import SGDClassifier

sgd = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', SGDClassifier()),
               ])
sgd.fit(X_train, y_train)

y_pred = sgd.predict(X_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred))

accuracy 0.9345794392523364
              precision    recall  f1-score   support

           0       0.86      0.94      0.90        32
           1       0.97      0.93      0.95        75

   micro avg       0.93      0.93      0.93       107
   macro avg       0.91      0.94      0.92       107
weighted avg       0.94      0.93      0.94       107



In [114]:
y_pred #  6wrong in sgd

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [115]:
np.array(y_test)

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [119]:
from sklearn.linear_model import LogisticRegression

logreg = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', LogisticRegression(n_jobs=1, C=1e5)),
               ])
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)
print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred))


accuracy 0.8878504672897196
              precision    recall  f1-score   support

           0       0.81      0.81      0.81        32
           1       0.92      0.92      0.92        75

   micro avg       0.89      0.89      0.89       107
   macro avg       0.87      0.87      0.87       107
weighted avg       0.89      0.89      0.89       107



In [120]:
y_pred #8 wrong in logreg

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [121]:
np.array(y_test) 

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1],
      dtype=int64)

In [145]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()



rf= Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', RandomForestClassifier()),
               ])
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred))

accuracy 0.9252336448598131
              precision    recall  f1-score   support

           0       0.88      0.88      0.88        32
           1       0.95      0.95      0.95        75

   micro avg       0.93      0.93      0.93       107
   macro avg       0.91      0.91      0.91       107
weighted avg       0.93      0.93      0.93       107



C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [158]:

from sklearn import svm

# Perform classification with SVM, kernel=linear
svm= svm.SVC()

svm= Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', RandomForestClassifier()),
               ])
svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)
print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred))

accuracy 0.9345794392523364
              precision    recall  f1-score   support

           0       0.86      0.94      0.90        32
           1       0.97      0.93      0.95        75

   micro avg       0.93      0.93      0.93       107
   macro avg       0.91      0.94      0.92       107
weighted avg       0.94      0.93      0.94       107



C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [174]:
data=[]
import pandas as pd
df=pd.read_excel("C:/Users/Dell/Pictures/senti/ml.xlsx")
# new instances where we do not know the answer
Xnew=df.content
# make a prediction
ynew = logreg.predict(Xnew)
# show the inputs and predicted outputs
for i in range(len(Xnew)):
    #print("X=%s, Predicted=%s" % (Xnew[i], ynew[i])) 
    data.append((Xnew,ynew))
cols=['Xnew','ynew']
result = pd.DataFrame(data, columns=cols)
#df['final_sentiment']= final_sentiment

In [187]:
c=Xnew.reset_index()


In [188]:
numpy_data = ynew
df = pd.DataFrame(data=numpy_data)


In [191]:
d=pd.merge(c,df1,on='index')

In [190]:
df1=df.reset_index()

In [194]:
d.to_excel("C:/Users/Dell/Pictures/rndpredicted.xlsx")

In [164]:
final_sentiment=[]
content=[]
import pandas as pd
df=pd.read_excel("C:/Users/Dell/Pictures/senti/ml.xlsx")
# new instances where we do not know the answer
Xnew=df.content
# make a prediction
ynew = svm.predict(Xnew)
# show the inputs and predicted outputs
for i in range(len(Xnew)):
    
    
    print("X=%s, Predicted=%s" % (Xnew[i], ynew[i]))   
    content.append(Xnew)
    final_sentiment.append(ynew)

X=good, Predicted=1
X=unexpectedlly    one bottle is damaged, Predicted=0
X=all these so called ayurvedic shampoos have all the chemicals in the book  then why call it ayurvedic  himalaya   patanjali and nyle all are one and the same dubious , Predicted=0
X=it s good for hair loss , Predicted=1
X=good, Predicted=1
X=good   but did not pack it properly    shampoo leaked in the package  , Predicted=1
X=not like, Predicted=0
X=as of now i m utilizing it    it makes your hair smooth and delicate  my hair is sleek so it makes my hair useful for     days  so in the event that anybody have dry hair they can utilize it   as it can make your hair smooth and delicate for couple of days , Predicted=1
X=the packing was not at all good  the bottle was not sealed and as a result shampoo was found ooing out of the bottle and inside of the parcel was slippery and wet  almost    to    ml of shampoo was lost  just a cellophane tap over the cap would have prevented this    star was given as it s not poss

In [ ]:
rules -sila neg kuda pos 4
model - log -partial
wrong class miss classfication severity high irukum pothu ethu crt ha predict panrathu eduthukalm. 

saying a +ve as -v_ve is not aproblem, 
but, saying a -ve sent as +ve is a major problem.